name:                cryptopals
version:             0.1.0.0
github:              "anrdh/cryptopals"
license:             BSD3
author:              "Aniruddh Agarwal"
maintainer:          "aaniruddh99@gmail.com"
copyright:           "2018 Aniruddh Agarwal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/anrdh/cryptopals#readme>

dependencies:
- base >= 4.7 && < 5
- base16-bytestring
- base64-bytestring
- bytestring
- bytestring-conversion
- binary
- text
- text-show
- cipher-aes
- random
- megaparsec
- containers
- safe
- lens
- bits
- vector
- time

library:
  source-dirs:
    - src

executables:
  cryptopals-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    dependencies:
    - cryptopals

tests:
  cryptopals-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptopals
